# Generated by Django 2.0.6 on 2018-06-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('intro', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('markdown_content', models.CharField(max_length=5000)),
                ('how_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.HowTo')),
            ],
        ),
    ]
