# Generated by Django 2.0.6 on 2018-06-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_howto_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='howto',
            old_name='title',
            new_name='title_test',
        ),
    ]
