# Generated by Django 2.0.6 on 2018-06-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180628_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='howto',
            old_name='title_test',
            new_name='title',
        ),
    ]
