# Generated by Django 2.0.6 on 2018-06-28 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180628_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now(), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
