# Generated by Django 2.0.6 on 2018-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_howto_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='published_status',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='howto',
            name='slug',
            field=models.CharField(default='this-is-a-slug', max_length=80),
            preserve_default=False,
        ),
    ]
