# Generated by Django 2.0.6 on 2018-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180628_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howto',
            name='published_status',
        ),
        migrations.AlterField(
            model_name='howto',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publish on'),
        ),
    ]
