# Generated by Django 2.0.6 on 2018-06-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='document',
            new_name='how_to',
        ),
    ]
