# Generated by Django 2.0.6 on 2018-06-28 20:09

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('polls', '0009_auto_20180628_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='how_to',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='slug',
        ),
        migrations.AddField(
            model_name='howto',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
