# Generated by Django 2.0.7 on 2018-07-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180628_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='howto',
            name='slug',
            field=models.CharField(default='slug-goes-here', max_length=80),
            preserve_default=False,
        ),
    ]
